apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecom-app
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: ecom-app
        tier: backend
        track: stable
    spec:
      containers:
      - image: ecom-app
        name: tsanderson77/ecom:backend
        ports:
         - name: http
           containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
    name: ecom-app
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: ecom-app
    tier: backend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecom-app
      tier: frontend
      track: stable
  template:
    metadata:
      labels:
        app: ecom-app
        tier: frontend
        track: stable
    spec:
      containers:
      - image: tsanderson77/ecom:backend
        name: ecom-app
        ports:
         - name: http
           containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: ecom-app
    tier: frontend
  type: LoadBalancer



