

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: dannydee93/eshopwebmvc:latest
          ports:
            - containerPort: 80        
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: publicapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: publicapi
  template:
    metadata:
      labels:
        app: publicapi
    spec:
      containers:
        - name: publicapi
          image: dannydee93/eshoppublicapi:latest
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/azure-sql-edge
          ports:
            - name: http
              containerPort: 1433   
          env:
            - name: SA_PASSWORD
              value: "@someThingComplicated1234"
            - name: ACCEPT_EULA
              value: "Y" 

