apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-service-v2
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: dannydee93/eshopwebmvc:latest
          ports:
            - name: http
              containerPort: 80  
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"

            
                   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service 
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: api
  template:
    metadata:  
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: dannydee93/eshoppublicapi:latest  
        env:
          - name: AZURE_KEY_VAULT_ENDPOINT
            value: k8s-default-ecommerc-82ce20c3f4-1378770920.us-east-1.elb.amazonaws.com
        ports:
            - name: http
              containerPort: 80
              containerPort: 433

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/azure-sql-edge
        ports:
        - containerPort: 1433
        # Add other container configuration as needed
        # ...
        env:
        - name: SA_PASSWORD
          value: "@someThingComplicated1234"
        - name: ACCEPT_EULA
          value: "Y"

---
