apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-service
spec:
  replicas: 2
  selector:
    matchLabels: kestrel-frontend
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: dannydee93/eshopwebmvc:latest
          ports:
            - containerPort: 80
            
                   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: dannydee93/eshoppublicapi:latest
          ports:
            - containerPort: 80
            - containerPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-service
spec:
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/azure-sql-edge
          ports:
            - name: http
              containerPort: 1433   
          env:
            - name: SA_PASSWORD
              value: "@someThingComplicated1234"
            - name: ACCEPT_EULA
              value: "Y" 

