apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshopwebmvc-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eshopwebmvc
  template:
    metadata:
      labels:
        app: eshopwebmvc
    spec:
      containers:
      - name: eshopwebmvc
        image: dannydee93/eshopwebmvc
        ports:
        - containerPort: 80
        - containerPort: 443
        # Add other container configuration as needed
        # ...

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshoppublicapi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eshoppublicapi
  template:
    metadata:
      labels:
        app: eshoppublicapi
    spec:
      containers:
      - name: eshoppublicapi
        image: dannydee93/eshoppublicapi
        # Add other container configuration as needed
        # ...

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/azure-sql-edge
        ports:
        - containerPort: 1433
        # Add other container configuration as needed
        # ...
        env:
        - name: SA_PASSWORD
          value: "@someThingComplicated1234"
        - name: ACCEPT_EULA
          value: "Y"

---
