apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: e-commerce-ingress
    annotations:
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: instance
        alb.ingress.kubernetes.io/tags: Environment=staging
    

spec:
  ingressClassName: alb
  rules:
    - host: k8s-default-ecommerc-e15c8f8fd7-2072327459.us-east-1.elb.amazonaws.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-service
                port:
                  number: 80


---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-app-to-azure
spec:
  podSelector:
    matchLabels:
      app: azure-key-vault-endpoint
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: web
        - podSelector:  
            matchLabels:
              app: api
