apiVersion: v1
kind: Service
metadata:
  name: d9-backend-service-nodeport
spec:
  type: NodePort
  selector:
    app: d9-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: d9-frontend-service-nodeport
spec:
  type: NodePort
  selector:
    app: d9-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
