apiVersion: v1
kind: Service 
metadata:
  name: web-service
spec:
  type: NodePort
  selector:
    app: web
  ports: 
  - protocol: TCP 
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: api
  ports:
  - protocol: TCP 
    port: 5200
    targetPort: 80
---
  

apiVersion: v1
kind: Service   
metadata:
  name: azure-key-vault-endpoint   
spec:
  type: NodePort 
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: azure-key-vault-endpoint


            
