apiVersion: v1
kind: Service 
metadata:
  name: kestrel-frontend-service
spec:
  type: NodePort
  selector:
    app: kestrel-frontend
  ports: 
  - protocol: TCP 
    port: 80
    targetPort: 80
  - protocol: TCP
    port: 443  
    targetPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: public-api-service
spec:
  type: NodePort
  selector:
    app: API.NET-backend
  ports:
  - protocol: TCP 
    port: 80
    targetPort: 80
  - protocol: TCP
    port: 443  
    targetPort: 443
