apiVersion: v1
kind: Service 
metadata:
  name: kestrel-frontend-service
spec:
  type: NodePort
  selector:
    app: kestrel-frontend
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: public-api-service
spec:
  type: NodePort
  selector:
    app: API.NET-backend
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
