apiVersion: v1
kind: Service
metadata:
  name: eshopwebmvc-service
spec:
  selector:
    app: eshopwebmvc
  ports:
    - protocol: TCP
      port: 5106
      targetPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: eshoppublicapi-service
spec:
  selector:
    app: eshoppublicapi
  ports:
    - protocol: TCP
      port: 5200
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver-service
spec:
  selector:
    app: sqlserver
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
