apiVersion: v1
kind: Service 
metadata:
  name: web-service
spec:
  type: NodePort
  selector:
    app: web
  ports: 
  - protocol: TCP 
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: api
  ports:
  - protocol: TCP 
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sql-serverservice
spec:
  selector:
    app: sqlserver
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433

