apiVersion: v1
kind: Service 
metadata:
  name: web-service
spec:
  type: NodePort
  selector:
    app: web
  ports: 
  - protocol: TCP 
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: api
  ports:
  - protocol: TCP 
    port: 443
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sql-service
spec:
  selector:
    app: sqlserver
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  

apiVersion: v1
kind: Service   
metadata:
  name: azure-key-vault-endpoint   
spec:
  type: NodePort 
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: azure-key-vault-endpoint

apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: aws-load-balancer-controller
  name: aws-load-balancer-webhook-service
  namespace: kube-system
spec:
  ports:
  - port: 443
    targetPort: 80
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: aws-load-balancer-controller
            
